# Generated by Django 4.1.5 on 2023-01-15 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('zip', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='fixedDiscount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='isFixed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentDiscount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
