# Generated by Django 4.1.5 on 2023-01-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_territory_alter_coupon_fixeddiscount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.territory'),
        ),
    ]
