# Generated by Django 4.1.5 on 2023-01-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_coupon_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='zip',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
